remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

title: "Heather L. Coates vitae"
description: "This page contains selected information from my vitae, with a focus on my research and service."
