remote_theme: chrisrhymes/bulma-clean-theme
$ bundle
plugins:
- jekyll-remote-theme 

title: "Heather L. Coates"
description: "Selected information from my vitae, with a focus on my research and service."
